replicaCount: 1

image:
  repository: kong
  tag: 2.8.1
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: 256Mi
    cpu: 200m
  limits:
    memory: 512Mi
    cpu: 500m

config:
  dashboardUsername: "supabase"
  dashboardPassword: "Huawei123"

# 钉到打了 role=data 标签的节点(hostPath 数据不漂移)
nodeSelector:
  role: "data"
